### ISSUE TITLE
Naming convention of files

### ISSUE THREAD

**Issue by faymanns** [NeLy-EPFL/DeepFly3D#26]
Currently the pose and prediction output files saved in the sub-folder are include the path to the directory in their name. This can lead to duplication of files when you work on the same data from different machines. For instance when a NAS is mounted in different locations as in the example below. The output sub-folder contains the following files:
```
-rwxr-xr-x 1 root root     3025 Feb  5 17:11 calib.pkl
-rwxr-xr-x 1 root root      184 Feb  5 16:57 cam_order.npy
-rwxr-xr-x 1 root root    13837 Feb  5 17:32 pose_corr_-mnt-data-CLC-190703_SS42740-tdTomGC6fopt-Fly2-CO2xzGG-behData_002-images-df3d_2.pkl
-rwxr-xr-x 1 root root 38453066 Feb  5 17:32 pose_result__mnt_data_CLC_190703_SS42740-tdTomGC6fopt_Fly2_CO2xzGG_behData_002_images.pkl
-rwxr-xr-x 1 root root 38453066 Dec 11 11:19 pose_result__mnt_NAS_CLC_190703_SS42740-tdTomGC6fopt_Fly2_CO2xzGG_behData_002_images.pkl
-rwxr-xr-x 1 root root  9047200 Dec 11 11:13 preds_-mnt-NAS-CLC-190703_SS42740-tdTomGC6fopt-Fly2-CO2xzGG-behData_002-images.pkl
```
I suggest we drop that part of the name and simply save them as `preds.pkl` and `pose_result.pkl`.
To ensure backwards compatibility we can glob for `preds*.pkl` and `pose_result*.pkl` and choose the file modified last.

**Comment by faymanns** [comment]
@semihgunel is there a reason you kept the path in the file name or is this just a remnant of the very early versions when you saved the output in a completely different folder?

**Comment by semihgunel** [comment]
This naming scheme is to make sure we don't ever forget where these files belong to. Perhaps it makes more sense to put this information in the file somehow.

df3d always reads the lastest files, so there shouldn't be any confusion on that side.

**Comment by faymanns** [comment]
> df3d always reads the lastest files, so there shouldn't be any confusion on that side.
That's good to know.

I agree that it's nice keep track of the folder which holds the images. Maybe we can only generate a new file name when no file exists and otherwise overwrite the old file.
