### ISSUE TITLE
Example JSON file with annotations?

### ISSUE THREAD

**Issue by lambdaloop** [NeLy-EPFL/DeepFly3D#28]
Hello,
I want to try running DeepFly3D on our dataset.
We already have annotations, so I think we could convert it to your JSON format to train a network and try out DeepFly3D.

However, I can't seem to find any example of a JSON annotation file of the type that [DeepFly3DAnnotation](https://github.com/NeLy-EPFL/DeepFly3DAnnotation) produces. 

Do you have any examples that you could share, perhaps on the H36M dataset?

**Comment by Sam-Kelly** [comment]
Hi,
We also tried to use their json file format for our data. I looked through to see if I still had any of the files from when we attempted this and all I found was this one.
[jsonfile.json.txt](https://github.com/NeLy-EPFL/DeepFly3D/files/5026061/jsonfile.json.txt)

In the end I converted deepfly3d to load CSV files similar to what deeplabcut uses.

**Comment by semihgunel** [comment]
@Sam-Kelly's file seems to be correct. Let me know if there is a problem.
