### ISSUE TITLE
Possible bug applies BP only to the left cameras

### ISSUE THREAD

**Issue by Sam-Kelly** [NeLy-EPFL/DeepFly3D#29]
https://github.com/NeLy-EPFL/DeepFly3D/blob/6764e082a3291bb69afac7b35bf53af2406c61cf/deepfly/GUI/main.py#L533
https://github.com/NeLy-EPFL/DeepFly3D/blob/6764e082a3291bb69afac7b35bf53af2406c61cf/deepfly/GUI/main.py#L550
https://github.com/NeLy-EPFL/DeepFly3D/blob/6764e082a3291bb69afac7b35bf53af2406c61cf/deepfly/GUI/main.py#L543
https://github.com/NeLy-EPFL/DeepFly3D/blob/6764e082a3291bb69afac7b35bf53af2406c61cf/deepfly/GUI/main.py#L556

I noticed that I was only getting BP automatic corrections for cameras 0,1,2 and not for cameras 4,5,6 and I think this might be why. 
Unless I'm misunderstanding what this function does, it's only applying the belief propagation to images in `self.image_pose_list` using `self.state.camNetLeft`, excluding everything from cameras 4,5,6 and the images in `self.image_pose_list_bot`

**Comment by semihgunel** [comment]
I think this can be resolved by replacing self.camNetLeft  with self.camNetAll under solve_bp. It seems this bug appeared once we split self.camNet into two parts and changed self.camNet to self.camNetAll.

**Comment by Sam-Kelly** [comment]
I solved this problem by changing the function signature to
`solve_bp(self, save_correction=False,side="left"):`

and adding
```
assert side in ["left", `"right"]
if side == "left":
    cam_net_this_side = self.state.camNetLeft
    image_pose_list_this_side = self.image_pose_list
elif side == "right":
    cam_net_this_side = self.state.camNetRight
    image_pose_list_this_side = self.image_pose_list_bot
```
to the function body, and changing references within the body to `camNetLeft` and `self.image_pose_list` to their new values. And making the appropriate changes in the places this method is called.
