### ISSUE TITLE
Search for .jpg is too general

### ISSUE THREAD

**Issue by jonasfbraun** [NeLy-EPFL/DeepFly3D#35]
DeepFly3D searches for all .jpg files in a sub-folder, but this seems to be too general to me.
If this search finds any .jpg that does not fulfill the camera_X_frame_YYYY.jpg pattern exactly, it throws an error.
In my case, I had a file called "camera_3_mean_img.jpg" in the images folder, which made DeepFly3D fail because os.util.parse_img_name() throws an error.
Here, the file name is very close to the original format and a ValueError is raised because "img" cannot be converted to int, but os.util.parse_img_name() would also fail with any other .jpg in the same folder as well.

I temporarily fixed the problem by making
os_utils.parse_img_name() return (-1, -1) instead of throwing an error and handling this case whenever os_utils.parse_img_name() was called, for example in pose2d.DrosophilaDataset.read_unlabeled_folder()
But I'm sure there's a better way, for example checking whether a file corresponds to the expected formatting scheme whenever searching through all .jpg files in the folder

**Comment by jbraun7** [comment]
Thanks!!

yes, that makes sense.
os_utils.parse_img_name() is called in other locations as well, not sure if it would be required there as well.

**Comment by sibowsb** [comment]
OK. I wanted to keep it more strict in case of similar filename confusions in the future.

PS. Syntactically you would want `.*_(\d+)_.*_(\d+).jpg` to accept any string instead of camera/img. `.` means any character and `*` means it can be repeated any number of times (including 0).

**Comment by sibowsb** [comment]
#36 is merged.
