### ISSUE TITLE
`test_missing_camera` is failing

### ISSUE THREAD

**Issue by jasper-tms** [NeLy-EPFL/DeepFly3D#44]
In `tests.py`, `test_missing_camera()` attempts to call `df3d-cli` on a folder that doesn't exist. I think some lines of code may be missing that prepare a folder with image data from only some cameras.

If anyone knows whether df3d is actually supposed to behave well will some missing cameras, or if this was a test that someone optimistically started writing without any actual implementation of the desired behavior in the package yet, let me know so I know whether to care about this test failing :sweat_smile:

**Comment by Dominic-DallOsto** [comment]
Yeah, I had the same problem / confusion. From what I can tell it isn't possible to run df3d at the moment with anything other than 7 cameras anyway?

**Comment by Dominic-DallOsto** [comment]
I redid the tests and removed this in #53
